### ISSUE TITLE
Error message on publishing to relays

### ISSUE THREAD

**Issue by pj8912** [swentel/nostr-php#30]
Error message I get when I try to publish note to public relays:

```
Fatal error: Uncaught WebSocket\TimeoutException: Client read timeout in /home/username/nostr-php-dev/nostrdev/vendor/textalk/websocket/lib/Connection.php:464 
Stack trace: 
#0 /home/username/nostr-php-dev/nostrdev/vendor/textalk/websocket/lib/Connection.php(166): WebSocket\Connection->read() 
#1 /home/username/nostr-php-dev/nostrdev/vendor/textalk/websocket/lib/Connection.php(115): WebSocket\Connection->pullFrame() 
#2 /home/username/nostr-php-dev/nostrdev/vendor/textalk/websocket/lib/Client.php(221): WebSocket\Connection->pullMessage() 
#3 /home/username/nostr-php-dev/nostrdev/vendor/swentel/nostr-php/src/Relay/
Relay.php(47):  WebSocket\Client->receive() #4 /home/username/nostr-php-dev/nostrdev/publish.php(66): swentel\nostr\Relay\Relay->send() #5 {main} thrown in /home/username/nostr-php-dev/nostrdev/vendor/textalk/websocket/lib/Connection.php on line 464
```
The error is when I try to publish to public relays. 
When I tried to publish to relay on my local machine at `ws://127.0.0.1:6969` it works. But not able to publish note to public relays.

**Comment by Sebastix** [comment]
Please let me know if you are still having issues with publishing events to public relays. If so, please share a code snippet so I can try reproduce it.
